EOF
#基础镜像使用jdk
FROM layker/jdk/openjdk:8-jdk-slim
#可以通过环境变量 自定义JVM参数
ENV JAVA_OPTIONS=""
ENV RUN_ARGS=""
WORKDIR /home/java
COPY ${deployment}.jar ${deployment}.jar
#挂载出日志目录
VOLUME /home/java
CMD java -Djava.security.egd=file:/dev/./urandom  ${RUN_ARGS} ${JAVA_OPTIONS} -jar ${deployment}.jar
EOF
