#基础镜像
FROM hub.hulushuju.com/jre/jre-8:8u191
#可以通过环境变量 自定义JVM参数
ENV JAVA_OPTIONS=""
WORKDIR /data/java
COPY ${deployment}.jar ${deployment}.jar
#挂载出日志目录
VOLUME /data/logs
CMD java -Djava.security.egd=file:/dev/./urandom  ${RUN_ARGS} ${JAVA_OPTIONS} -jar ${deployment}.jar